### ISSUE TITLE
error of plog()

### ISSUE THREAD

**Issue by zhengyanstu** [moold/ParallelTask#8]
Dear Developer，
I hope this message finds you well. I am writing to seek assistance regarding an issue I encountered while using paralleltask. The error message I received is as follows:
File "/home/trim/NextPolish/nextPolish", line 11, in <module>
   from paralleltask import Task
File "/home/miniconda3/envs/allhic/lib/python3.9/site-packages/paralleltask/__init__.py", line 1, in <module>
   from paralleltask.task_control import Task
File "/home/miniconda3/envs/allhic/lib/python3.9/site-packages/paralleltask/task_control.py", line 19, in <module>
   log = plog()
NameError: name 'plog' is not defined 

Upon reviewing the task_control.py file, it appears that the issue might be related to the following lines:
try:
        from kit import *
except ImportError:
        from paralleltask.kit import *

I am unsure how to resolve this problem. Would it be advisable for me to remove the top three lines and retain only "from paralleltask.kit import *"? Your guidance on resolving this matter would be greatly appreciated.

Thank you for your time and assistance.

**Comment by moold** [comment]
Could you try to install paralleltask by `pip install paralleltask` and do some testing as [here](https://github.com/moold/ParallelTask?tab=readme-ov-file#testing) ?

**Comment by zhengyanstu** [comment]
> Could you try to install paralleltask by `paralleltask` and do some testing as [here](https://github.com/moold/ParallelTask?tab=readme-ov-file#testing) ?

I installed it with "pip install paralleltask". What is "install paralleltask by paralleltask"?

I have done testing but the test was failed. It shows:
Command '/bin/bash /home/temp/test.sh.work/work00/work0006/subtask.sh > /home/temp/test.sh.work/work00/work0006/subtask.sh.o 2> /home/temp/test.sh.work/work00/work0006/subtask.sh.e' returned non-zero exit status 2, error info: .
Traceback (most recent call last):
  File "/home/miniconda3/envs/allhic/bin/paralleltask", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/allhic/lib/python3.9/site-packages/paralleltask/__main__.py", line 148, in main
    run(args)
  File "/home/miniconda3/envs/allhic/lib/python3.9/site-packages/paralleltask/__main__.py", line 66, in run
    task.run.start()
  File "/home/miniconda3/envs/allhic/lib/python3.9/site-packages/paralleltask/task_control.py", line 348, in start
    self._start()
  File "/home/miniconda3/envs/allhic/lib/python3.9/site-packages/paralleltask/task_control.py", line 372, in _start
    self.submit(job)
  File "/home/miniconda3/envs/allhic/lib/python3.9/site-packages/paralleltask/task_control.py", line 252, in submit
    _, stdout, _ = self.run(job.cmd)
  File "/home/miniconda3/envs/allhic/lib/python3.9/site-packages/paralleltask/task_control.py", line 292, in run
    log.critical("Command '%s' returned non-zero exit status %d, error info: %s." % (cmd, p.returncode, stderr))
  File "/home/miniconda3/envs/allhic/lib/python3.9/logging/__init__.py", line 1493, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/home/miniconda3/envs/allhic/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/home/miniconda3/envs/allhic/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/home/miniconda3/envs/allhic/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/home/miniconda3/envs/allhic/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/home/miniconda3/envs/allhic/lib/python3.9/site-packages/paralleltask/kit.py", line 42, in emit
    raise Exception(record.msg)
Exception: Command '/bin/bash /home/temp/test.sh.work/work00/work0006/subtask.sh > /home/temp/test.sh.work/work00/work0006/subtask.sh.o 2> /home/temp/test.sh.work/work00/work0006/subtask.sh.e' returned non-zero exit status 2, error info: .
^C[66108 WARNING] 2023-12-08 17:07:14 Accepted a killed signal and killing all running jobs, please wait...
[66108 WARNING] 2023-12-08 17:07:14 Killed all running jobs done
[66108 WARNING] 2023-12-08 17:07:14 Exit!

**Comment by moold** [comment]
Can you manually run the command `/bin/bash /home/temp/test.sh.work/work00/work0006/subtask.sh > /home/temp/test.sh.work/work00/work0006/subtask.sh.o 2> /home/temp/test.sh.work/work00/work0006/subtask.sh.e` to see what is going on?

**Comment by zhengyanstu** [comment]
> Can you manually run the command `/bin/bash /home/temp/test.sh.work/work00/work0006/subtask.sh > /home/temp/test.sh.work/work00/work0006/subtask.sh.o 2> /home/temp/test.sh.work/work00/work0006/subtask.sh.e` to see what is going on?

I ran that command, and open the "subtask.sh.e" file.
It shows :
"
hostname
+ hostname
cd /home/temp/test.sh.work/work00/work0006
+ cd /home/temp/test.sh.work/work00/work0006
( time  <link rel="dns-prefetch" href=/home/temp/"https:/avatars.githubusercontent.com"> )
subtask.sh: line 5: syntax error near unexpected token `)'
“

**Comment by moold** [comment]
So, your working shell is not a legal shell script.

**Comment by zhengyanstu** [comment]
> So, your working shell is not a legal shell script.

No worries, it seems like there was a typo in test.sh

**Comment by CJ-Miao** [comment]
I also encounter this problem, when I use ParellelTask, it bump this error
$  paralleltask  -h
Traceback (most recent call last):
  File "/home/xxx/miniconda3/bin/paralleltask", line 5, in <module>
    from paralleltask.__main__ import main
  File "/home/xxx/miniconda3/lib/python3.9/site-packages/paralleltask/__init__.py", line 1, in <module>
    from paralleltask.task_control import Task
  File "/home/xxx/miniconda3/lib/python3.9/site-packages/paralleltask/task_control.py", line 19, in <module>
    log = plog()
NameError: name 'plog' is not defined       

When I see the content of task_control.py, it seems like plog() is not defined?
